# Generated by Django 2.2.1 on 2019-05-26 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('fabricante', models.CharField(max_length=70)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
        ),
    ]
